### ISSUE TITLE
[BUG] hookzones bug

### ISSUE THREAD

**Issue by Ciallo-Ani** [surftimer/Surftimer-Official#108]
every hookzone couldn't activate "filter_activator_name"
i mean,while i'm touching a trigger with targetname "xxx",hookzone couldn't activate it,which means that i couldn't get teleport or push(eg:surf_rands all stages)

**Comment by dPexxIAM** [comment]
change the zones targetname to the same targetname applied to the trigger, EG:

"model" "*148"
"wait" "1"
"targetname" "b1_start"
"StartDisabled" "0"
"spawnflags" "1"
"origin" "5008 0 4688"
"classname" "trigger_multiple"
"hammerid" "137781"
"OnStartTouch" "!activatorAddOutputtargetname b10-1"

You would change the zones targetname to "b1"

use stripper to run a dump on the map to find these values.

Changing the targetname can be done via edit zones option in !zones menu, else via your databases ck_zones table 

The same issue is present with filters, the activator is not applied when player fails/respawns, to stop this from happening, you can change the zones targetname to something other than "player" it can be named to any targetname you wish.

**Comment by sneak-it** [comment]
I'm going to re-open and re-label this since it's far from ideal, while there is a workaround available, I believe our ideal approach should be copying the relevant trigger kv's when hooking & recreating the trigger.

**Comment by Ciallo-Ani** [comment]
someone mentioned it again, and i find it unneccessary to set player's targetname when they start to touch ck_zones,while ck_zones' targetname is neccessary

i couldn't tell more about it, but delete some code implemented badly should be ok.

i haven't test it :d

https://github.com/surftimer/Surftimer-Official/blob/master/addons/sourcemod/scripting/surftimer/surfzones.sp#L225

**Comment by dPexxIAM** [comment]
https://github.com/surftimer/Surftimer-Official/pull/280

Tested, the outputs get applied just fine now. Someone else should also test, though.
