### ISSUE TITLE
[Suggestion] Speed Limit Zone

### ISSUE THREAD

**Issue by sneak-it** [surftimer/Surftimer-Official#114]
**Is your feature request related to a problem? Please describe.**
Superboosting. The source engine sucks and allows you to activate triggers more often than you should.

**Describe the solution you'd like**
Since there is really no clear-cut way to eliminate superboosting, so a zone with a determined allowed max velocity would be ideal for server owners/zoners. This would invalidate map/bonus/stage timers if passed through at a higher than acceptable speed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dPexxIAM** [comment]
There are no-jump zones & max-speed zones built into the timer already, however, neither of them work as intended.

**Comment by stunslave** [comment]
The max-speed zone doesn't allow the speed to go over 2500 for some reason intended or another bug?

**Comment by timyc** [comment]
You can "fix" the maxspeed zones by replacing line 873 in hooks.sp with "LimitMaxSpeed(client, g_mapZones[g_iClientInZone[client][3]].PreSpeed);"

However, these zones only work according to a player's ping, so it will cause issues with higher ping players. If this zone is placed in close proximity to another zone, the other zone won't trigger either if the player has high ping (which causes issues on maps like the starting stage of surf_holiday).
