### ISSUE TITLE
[BUG] Hook Zoning Exception

### ISSUE THREAD

**Issue by CustomStats** [surftimer/Surftimer-Official#133]
**Describe the bug**
When zoning with a Hook Zone, you are only able to use this option once and any attempts after will give you a handle error and the menu will close upon pressing "4. Hook Zone". Retrying allowed me to do it again but eventually stopped working even after retrying. 

**Expected behavior**
Ability to use Hook Zone multiple times

**Screenshots**
https://streamable.com/8jbgyz

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
285.9

**Additional context**
```
[SM] Exception reported: Menu handle ab1802a0 is invalid (error 1)
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] DisplayMenu
[SM]   [1] Line 4292, surftimer/commands.sp::HookZonesMenu
[SM]   [2] Line 1601, surftimer/surfzones.sp::Handle_SelectNormalZoneType
```

**Comment by FR33K1LL** [comment]
can confirm im also getting this error. on 285.95

**Comment by TheGunter24** [comment]
still happening in latest dev. 1.0.2 (at https://github.com/surftimer/Surftimer-olokos/commit/e9818d01c64ed4411c6510c36141b222fa9f3b00 date)

i think this is breaking, a fast fix would be nice

**Comment by FR33K1LL** [comment]
Well what i did to solve this for now is this
https://github.com/surftimer/Surftimer-olokos/commit/ec5b7350b7b39a08afb903265df98cb720d5cba4#r39433688

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by TheGunter24** [comment]
for me it works now

**Comment by FR33K1LL** [comment]
This was already confirmed fixed on july 30th
