### ISSUE TITLE
[BUG] 1 jump limit and prespeed limit are not respected on LG and SM

### ISSUE THREAD

**Issue by bali2k** [surftimer/Surftimer-Official#153]
**Describe the bug**
1 jump limit and prespeed limit is not respected on Low-Gravity and Slow Motion.

**Expected behavior**
You should be able to jump only once in zone with "1 jump limit" setting enabled like on styles with normal timescales and gravity. Also same with prespeed.

**Screenshots**
N/A

**Plugin List**
N/A

**Timer Version**
Master

**Additional context**
I noticed that if you leave zone and go back on LG and SM style your speed decreases to setted prespeed but 1 jump limit still doesn't work after doing this.

**Comment by Bara** [comment]
Fixed in master-Branch
