### ISSUE TITLE
[BUG] Chat message about missing your PB

### ISSUE THREAD

**Issue by bali2k** [surftimer/Surftimer-Official#154]
**Describe the bug**
Chat message about "missing your PB" displays missed PB from Normal style even when you're playing on other style.

**Expected behavior**
It should display missed PB from currently used style.

**Screenshots**
![image](https://user-images.githubusercontent.com/63168637/82742569-5f544180-9d60-11ea-8a1e-ad73a8f028e2.png)

**Plugin List**
N/A

**Timer Version**
Master branch

**Additional context**
N/A

**Comment by qawery-just-sad** [comment]
i mean it's techincly correct you missed your pb xD

**Comment by qawery-just-sad** [comment]
so if someone wanna fix this it's [here](https://github.com/surftimer/Surftimer-olokos/blob/347c136ef36577f1cb74bed5dc6493512275e5ec/addons/sourcemod/scripting/surftimer/misc.sp#L2846) and [here for bonus](https://github.com/surftimer/Surftimer-olokos/blob/347c136ef36577f1cb74bed5dc6493512275e5ec/addons/sourcemod/scripting/surftimer/misc.sp#L2864) just make sure that `g_fPersonalRecord` also checks for style (i think `g_iCurrentStyle[client]` but not so sure)

**Comment by qawery-just-sad** [comment]
Fixed by merging #241
