### ISSUE TITLE
[BUG] sm_hide not working on bots

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-Official#155]
**Describe the bug**
Cant hide bots - All bots are visible (sm_hide only hides players).

**Screenshots**
https://i.imgur.com/SPpJbtg.png

**Timer Version**
285.95 (latest dev)

**Comment by sneak-it** [comment]
Can you or someone else test and see if this happens on the latest commit of the dev branch? @stunslave

**Comment by Bara** [comment]
hidebot branch or not? 🤔

**Comment by FR33K1LL** [comment]
I can test in a couple days if no one else does by then.

**Comment by sneak-it** [comment]
[**@Bara**](https://github.com/Bara) commented on [Aug 20, 2020, 8:31 PM EDT](https://github.com/surftimer/Surftimer-olokos/issues/155#issuecomment-677972857 "2020-08-21T00:31:23Z - Replied by Github Reply Comments"):
> hidebot branch or not? 🤔

Nope, dev :)

**Comment by Bara** [comment]
https://github.com/surftimer/Surftimer-olokos/commits/dev
🤔
