### ISSUE TITLE
[BUG] Vote Extend Bug

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-Official#169]
**Describe the bug**
_If one player votes NO the vote fails._
As shown in the image below 3 players total,  2 players vote yes and one player votes no, which causes the vote to fail. Tested several times on several servers.
Vote is passed when all players vote yes.

**Screenshots**
![image](https://user-images.githubusercontent.com/47533535/83460096-e6db3800-a465-11ea-8e83-323402e58429.png)

**Timer Version**
Latest dev

**Comment by bctse** [comment]
Can confirm I get the same issue with 285.95

**Comment by olokos** [comment]
Can you try with 1.0.0?

**Comment by olokos** [comment]
1.0.1 released @stunslave
