### ISSUE TITLE
[Suggestion] Discord/SMJansson Requirement Optional

### ISSUE THREAD

**Issue by sneak-it** [surftimer/Surftimer-Official#19]
**Is your feature request related to a problem? Please describe.**
No problem, this suggestion improves compatibility with people's setups.

**Describe the solution you'd like**
Let's make the Discord API requirement optional based upon a cvar switch. This would make the SMJansson extension requirement also optional.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sneak-it** [comment]
Just a follow-up - moving the Discord announcer into a separate module would probably make more sense.

**Comment by Bara** [comment]
#240
