### ISSUE TITLE
[BUG] can't search other map tops

### ISSUE THREAD

**Issue by rosekick** [surftimer/Surftimer-Official#209]
for example,i type !maptop surf_sinister2 but appear nothing

**Timer Version**
Prerelease 1.0.2 - development version

**Additional context**
L 07/12/2020 - 21:40:35: [SM] Blaming: SurfTimer.smx
L 07/12/2020 - 21:40:35: [SM] Call stack trace:
L 07/12/2020 - 21:40:35: [SM]   [1] Line 8760, surftimer/sql.sp::sql_selectMapNameLikeCallback

**Comment by sneak-it** [comment]
You cut off the actual error, please provide the whole error log.

**Comment by olokos** [comment]
I tried to reproduce this bug on my server running current dev code, but it works just fine, I don't have a record for that map in particular, but I took surf_kitsune as an example.

![Image](https://image.prntscr.com/image/KWexctpUROiE_-YnjBKD4g.png)

**Comment by olokos** [comment]
The issue is valid actually and the bug is still present on dev branch.

I think it has something to do with longer mapnames as `surf_kitsune` works but `surf_how2` ends up in the following stack trace:
```
L 07/29/2020 - 02:13:46: [SM] Exception reported: Array index out-of-bounds (index 153, limit 66)
L 07/29/2020 - 02:13:46: [SM] Blaming: SurfTimer.smx
L 07/29/2020 - 02:13:46: [SM] Call stack trace:
L 07/29/2020 - 02:13:46: [SM]   [1] Line 8806, surftimer/sql.sp::sql_selectMapNameLikeCallback
L 07/29/2020 - 02:14:00: [SM] Exception reported: Array index out-of-bounds (index 153, limit 66)
L 07/29/2020 - 02:14:00: [SM] Blaming: SurfTimer.smx
L 07/29/2020 - 02:14:00: [SM] Call stack trace:
L 07/29/2020 - 02:14:00: [SM]   [1] Line 8806, surftimer/sql.sp::sql_selectMapNameLikeCallback
```

**Comment by olokos** [comment]
I think it's either
https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L8779
or 
https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L8788

Will do testing later.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version?

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sq](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)l-File.

**Comment by olokos** [comment]
I just did reproduce it with latest dev version.

I had server running, but empty so I was on the server, wrote `quit` in server console and joined ASAP as the server was visible, leading to this:

```
L 11/07/2020 - 00:02:21: [surftimer] Starting to load server settings
L 11/07/2020 - 00:02:22: [SurfTimer] Finished loading server settings in 0.750000s
PutClientInServer: no info_player_start on level
L 11/07/2020 - 00:02:22: [Surftimer] Loading STEAM_1:0:58950181 - olopros settings
RecordSteamInterfaceCreation (PID 14201): SteamGameStats001 /
L 11/07/2020 - 00:02:22: [randomcycle.smx] RandomCycle has chosen surf_mjk for the nextmap.
L 11/07/2020 - 00:02:22: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalRecords in 0.109375s
ConVarRef sv_voice_proximity_minvolume doesn't point to an existing ConVar
L 11/07/2020 - 00:02:23: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalBonusRecords in 0.359375s
L 11/07/2020 - 00:02:23: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalStageRecords in 0.015625s
L 11/07/2020 - 00:02:23: [SurfTimer] STEAM_1:0:58950181: Finished db_viewPlayerPoints in 0.593750s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_GetPlayerRank in 0.281250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewPlayerOptions in 0.031250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_CheckVIPAdmin in 0.015625s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewCustomTitles in 0.031250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewCheckpoints in 0.015625s
L 11/07/2020 - 00:02:24: [SurfTimer] Finished loading STEAM_1:0:58950181 - Pending Vote (in Time: 29:52) settings in 1.453125s
```

**Comment by olokos** [comment]
This bug doesn't happen anymore on current dev branch, the only issue I could find is that Community profile links doesn't really do much right now

![Image](https://image.prntscr.com/image/ZDCg8-XSQvWxVvCVGxoOoQ.png)
But that's unrelated and this issue can be closed.
