### ISSUE TITLE
[BUG] Default titles not working correctly

### ISSUE THREAD

**Issue by qawery-just-sad** [surftimer/Surftimer-Official#227]
**Describe the bug**
Some users experience that while setting `ck_enforce_default_titles = 1` and default_titles.txt like in example below
```
"Default Titles"
{
  "0"
  {
    "steamid" "STEAM_1:X:XXXXXXXXX"
    "title" "{default}[{red}Owner{default}]"
    "type" "chat"
  }
}
```
The `"type" "chat"` is not respected and falls back to `"both"` which is default.

**Expected behavior**
Respect `chat` type.

**Screenshots**

**Plugin List**
SurfTimer dev 1.0.2

**Additional context**
Might have something to do with chat processor (or imo `ck_vipadmins` overwriting those settings)
https://discordapp.com/channels/366959507764674560/379572504542445568/743897854745116830

I just passed the issue from discord, I don't know anything more, ask ApollonV2K#7343 on discord

**Comment by TheGunter24** [comment]
with latest version https://github.com/surftimer/Surftimer-olokos/commit/03edad48dd31b087ccfa38869f22ddf4b6c09982
i still get this bug, as seen in screenshot. type is set to "chat" 
![20200831215008_1](https://user-images.githubusercontent.com/23201164/91763838-7cf23c00-ebd6-11ea-8677-b3c49060c908.jpg)
