### ISSUE TITLE
[Suggestion] !wipeplayer for SurfTimer

### ISSUE THREAD

**Issue by freakexeuLow** [surftimer/Surftimer-Official#229]
I have no idea if anyone had ever said this before, but I wrote it to Bara privately, unfortunately we are old and forget such things very quickly, so I write it here...if possible, there should be a !wipeplayer STEAMID command (sometime when well many problems are fixed). The same already exists with the Bhoptimer aka "Spaghetti" Timer by Shavit : [https://github.com/shavitush/bhoptimer](https://github.com/shavitush/bhoptimer). I like the system because there are some users that I ban and would like to delete their record this way instead of doing it all in the database.

that's all

**Comment by dPexxIAM** [comment]
https://github.com/nikooo777/ckSurf/blob/master/csgo/addons/sourcemod/scripting/ckSurf.sp#L2009

Existed before & was removed. Update the queries for this command & I guess it will merge without issues
