### ISSUE TITLE
[BUG] 1.1.0 Dev Version (Problems)

### ISSUE THREAD

**Issue by freakexeuLow** [surftimer/Surftimer-Official#242]
**Describe the bug**

The server record does not match the maptop rank

**Screenshot**
 [https://i.gyazo.com/7a910e5a74d5865153ae7c82bba34b06.png](https://i.gyazo.com/7a910e5a74d5865153ae7c82bba34b06.png)

**Plugin List**
SurfTimer 1.1.0 Dev Version
MomSurfFix

I will test every update in the near future, I will get players to test it with me, should there be any further problems, I will send you here in this post :3

**Comment by Bara** [comment]
I've splitted this issue into 2.

**Comment by Kyli3Boi** [comment]
Just tested this issue with the latest build and to add more info the time on the left side menu is the correct time and the time that is displayed in the center hud is incorrect

**Comment by freakexeuLow** [comment]
was tested and has my okay, it works again 👍🏼 

thanks Bara

**Comment by Kyli3Boi** [comment]
Can confirm, also tested and is working correctly

**Comment by LubricantJam** [comment]
@freakexeuLow if you could report back whether the latest dev version is somewhat stable, I'll put this on my servers and run it also to get a wedge of data.

**Comment by freakexeuLow** [comment]
@LubricantJam currently I have this running on my test server, I will write to you at Discord when I have tested it for 1-2 weeks

**Comment by LubricantJam** [comment]
I am assuming also, scoreboard ranks were removed for a reason?

![Image](https://lubricantjam.com/uploads/2020/09/24/csgo_2020-09-24_21-28-02.png)

**Comment by Bara** [comment]
But that's not the part of this issue 🤔

**Comment by freakexeuLow** [comment]
> 
> 
> I am assuming also, scoreboard ranks were removed for a reason?
> 
> ![Image](https://camo.githubusercontent.com/9162dc1a17c7722e4cda4713de2dc002315975bd/68747470733a2f2f6c7562726963616e746a616d2e636f6d2f75706c6f6164732f323032302f30392f32342f6373676f5f323032302d30392d32345f32312d32382d30322e706e67)

This is a different problem jam, here in this thread it was about the Hud display (Server Record) that this was not correct :3

**Comment by LubricantJam** [comment]
Gotcha, just read "problems" and assumed it was a general topic, my b g.

**Comment by freakexeuLow** [comment]
> 
> 
> Gotcha, just read "problems" and assumed it was a general topic, my b g.

Yes, it is best to open a new issue, I have also learned from this to post problems individually ^^
