### ISSUE TITLE
[BUG] Scoreboard Tags

### ISSUE THREAD

**Issue by freakexeuLow** [surftimer/Surftimer-Official#256]
**Describe the bug**
With the 1.10 version it is no longer possible to see the player tags (skill groups)

**Screenshots**
![20200927142842_1](https://user-images.githubusercontent.com/32603929/94365045-145f8780-00ce-11eb-9b9c-2e9103407db5.jpg)

**Plugin List**
SurfTimer 1.10 dev version
MomSurfFix

**Comment by TheGunter24** [comment]
+1 
have you tried using "default_titles" for the chat tag ?
i just get this: 
![20200927153809_1](https://user-images.githubusercontent.com/23201164/94366302-90120200-00d7-11eb-834b-1d2f2793e475.jpg)

**Comment by freakexeuLow** [comment]
Hhey Günther aka Kitty Mod^^ the cfg is on default, do you use the latest version with the Uprade Script because you have the 99999 Bug????

**Comment by TheGunter24** [comment]
> Hey Günther aka Kitty Mod^^ the cfg is on default, do you use the latest version with the Uprade Script because you have the 99999 Bug????
> 
> Edit: no matter if 1 or 0, it always looks the same and this applies only to normal users
> 
> ```
> // Sets whether default titles will be enforced on clients, Enable / Disable
> // -
> // Default: "0"
> ck_enforce_default_titles "0"
> ```

I am using the newest Version, Inc. The DB Changes.
The 9999 Bug is anoying but not breaking. Since it fixes itself after "updating" this Rankinginfo. 

And its gUnter not ü, + kittEy not kitty 😅

**Comment by Kyli3Boi** [comment]
The rank bug was fixed some time ago #222 so i doubt you are using the latest version

**Comment by TheGunter24** [comment]
> The rank bug was fixed some time ago #222 so i doubt you are using the latest version

Ive updated all Files🙄
Maybe i overlooked Something, will Check next Weekend

**Comment by TheGunter24** [comment]
update:
when using the latest version https://github.com/surftimer/Surftimer-Official/commit/d3882acceb018c82e679f440df2d6b4cf2e5e7a4 it all works fine for me.
default titles and skillgroup ranks, in chat / scoreboard ^^
![20201003102947_1](https://user-images.githubusercontent.com/23201164/94987043-b9151580-0563-11eb-9e7b-d44e485e1b05.jpg)
![20201003103006_1](https://user-images.githubusercontent.com/23201164/94987045-b9adac00-0563-11eb-8c40-b3a45b09999c.jpg)

**Comment by TheGunter24** [comment]
nevermind, when testing on live server it is indeed bugged and the scoreboard tag is gone (default works)

**Comment by olokos** [comment]
Can confirm this bug on latest dev branch with latest requirements and includes
![Bug image](https://image.prntscr.com/image/YR-gF3S3ShOV73jImrki0g.png)

**Comment by olokos** [comment]
Is this bug still present with latest master branch code?

**Comment by freakexeuLow** [comment]
> Is this bug still present with latest master branch code?

Nope, last stable and also the master do not have this problem anymore
