### ISSUE TITLE
[BUG] CANT CHANGE IMPROVEMENT SOUNDS

### ISSUE THREAD

**Issue by barzbug** [surftimer/Surftimer-Official#259]
**Describe the bug**
I tried to changing improvement sounds. I made edits on surftimer.cfg and I uploaded my new record "improvements" sounds. 
But it didn't. Sometimes the sounds don't change, they stay the same. Sometimes there is no sound at all.

**Expected behavior**
I want to upload my own record sounds. "NEW WORLD RECORD (MAN VOICE)" "NEW PERSONAL BEST (MAN VOICE) etc..
.

**Screenshots**
Do not need

**Plugin List**
Do not need

**Additional context**
wr.mp3 pb.mp3 top10.mp3 I make the names the same and change the files but it still doesn't work

**please help me**

**Comment by freakexeuLow** [comment]
the sounds must not have the same name, I also use other sounds and it works perfect

**Comment by barzbug** [comment]
> the sounds must not have the same name, I also use other sounds and it works perfect

I tried it with different names. Unfortunately it didn't work

**Comment by Kyli3Boi** [comment]
This doesnt sound like a bug this sounds like a problem you are having and for that you should use the discord

**Comment by freakexeuLow** [comment]
> 
> 
> > the sounds must not have the same name, I also use other sounds and it works perfect
> 
> I tried it with different names. Unfortunately it didn't work

like I said, I have tested it on 2.8.5 and on dev, it works 100% without problems

**Comment by barzbug** [comment]
I've banned at discord please help me here
