### ISSUE TITLE
[BUG] Players cant do !r !b or !s commands etc.

### ISSUE THREAD

**Issue by barzbug** [surftimer/Surftimer-Official#260]
**Describe the bug**

When the server comes to a certain number of players, 1 or 2 players have a bug on some maps. For example, when they type the command! Restart, nothing happens. When they fall to the ground, they cannot turn back. No commands are working. They just just stay there. When they type "retry" to the console several times, it just gets better. Or it gets better when you open and close the game. Then this problem spreads like a virus to other newcomers.

**Expected behavior**
I want this problem to go away

**Screenshots**
We can't show that

**Plugin List**
Surftimer

**Additional context**

**Comment by Kyli3Boi** [comment]
This again doesnt sound like a bug but a problem you are having and should use the discord. If this was a bug it would have been reported a very very long time ago

**Comment by barzbug** [comment]
I've banned at discord please help me here
