### ISSUE TITLE
[BUG] About replay bots

### ISSUE THREAD

**Issue by barzbug** [surftimer/Surftimer-Official#264]
Fuck the creator of this plugin, those who opened a help topic and didn't help, all the moderators and administrators on discord servers, and all the dogs that deleted my help requests from this site.

**Comment by Bara** [comment]
Don't be rude.

**Comment by qawery-just-sad** [comment]
m8 create another acc on dc and stop the salt machine, also your issues are so generic look up the tutorial on yt
