### ISSUE TITLE
[BUG] Unable to compile the surftimer

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-Official#271]
**Describe the bug**
Prerelease 1.0.2 - development version
Prerelease 1.0.0 - development version
Cant compile the surftimer in either of the versions above.

**Plugin List**
Sourcemod 1.10 - build 6502
Metamod 1.11 - build 1144

**Screenshots**
Screenshot of compile errors.
![image](https://user-images.githubusercontent.com/47533535/105006894-ecf74680-5a3f-11eb-872d-babba297dbc8.png)

**Additional context**
N/A

**Comment by stunslave** [comment]
Didnt find a fix. 
Wont bother using new discord annoucements, will stick to old.

**Comment by olokos** [comment]
You literally just wrote the fix to the issue you're having. 😄

**Comment by stunslave** [comment]
The problem was the include that came with the timer wouldn't compile, I had to jump back to a older version of the discord include (message_embed.inc) from late 2019 on a random git users rep to make the plugin compile with the new embed code. Random shit.
