### ISSUE TITLE
[Suggestion] Discord Bonus Images

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-Official#272]
**Describe the solution you'd like**
If possible.. add a cvar to allow per bonus announcement discord images.. 

A different image for each bonus announcement on discord.
The current images are kewl, but get rather repetitive. :P

**Additional context**
Each image will be named with a prefix..  Bonus 1 = _b1 , Bonus 2 = _b2 etc
Example: surf_pls_b1.jpg, surf_pls_b2.jpg, surf_pls_b3.jpg etc

The cvar can be the location where the bonus images are located and maybe a cvar to use either a single bonus image for all bonuses or to use per bonus images.

Coding this may take a while. (I cant code for shit).

If anyone needs discord images: https://csgo.specternetworks.com/fastdl/maps/images/map_images.rar (you will need to rename them though)

**Comment by Sarrus1** [comment]
This was implemented in [the Discord module](https://github.com/Sarrus1/SurfTimer-discord).
