### ISSUE TITLE
[BUG]how to avoid this?

### ISSUE THREAD

**Issue by edyedyy** [surftimer/Surftimer-Official#273]
https://imgur.com/a/HIC0AZd . I have a HUD plugin . How can I avoid this?

**Comment by qawery-just-sad** [comment]
Not really sure what's the issue coz u showed half of your screen but i can say that there are two solutions: 
1. uninstall that plugin
2. disable centre hud and centre speed

**Comment by olokos** [comment]
No template used, no info provided, so I'm closing this.
