### ISSUE TITLE
[SOLVED] [BUG] Ranks from ck_playerrank gets deleted after server shut down

### ISSUE THREAD

**Issue by S0ulan** [surftimer/Surftimer-Official#278]
**Describe the bug**
Ranks from ck_playerrank gets deleted after server shut down. The table is empty afterwards.

Ubunutu
MYSQL: mysql  Ver 14.14 Distrib 5.7.33, for Linux (x86_64) using  EditLine wrapper

**Expected behavior**
Should keep the data in the table

**Plugin List**
meta version
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1144
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Dec 27 2020 18:18:22

 SourceMod Version Information:
    SourceMod Version: 1.10.0.6502
    SourcePawn Engine: 1.10.0.6502, jit-x86 (build 1.10.0.6502)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Dec 18 2020 04:15:26
  [01] SourceMod (1.10.0.6502) by AlliedModders LLC
  [02] CS Tools (1.10.0.6502) by AlliedModders LLC
  [03] SDK Tools (1.10.0.6502) by AlliedModders LLC
  [04] SteamWorks Extension (1.2.3) by Kyle Sanderson
  [05] DHooks (2.2.0) by Dr!fter
  [06] SDK Hooks (1.10.0.6502) by AlliedModders LLC

[SM] Listing 23 plugins:
  01 "Basic Comm Control" (1.10.0.6502) by AlliedModders LLC
  02 "Anti-Flood" (1.10.0.6502) by AlliedModders LLC
  03 "Fix Hint Color Messages" (1.0.1) by Phoenix (˙·٠●Феникс●٠·˙) and Franc1sco Franug
  04 "Chat-Processor" (2.2.2) by Drixevel
  05 "Admin Menu" (1.10.0.6502) by AlliedModders LLC
  06 "Reserved Slots" (1.10.0.6502) by AlliedModders LLC
  07 "Basic Info Triggers" (1.10.0.6502) by AlliedModders LLC
  08 "Sound Commands" (1.10.0.6502) by AlliedModders LLC
  09 "Player Commands" (1.10.0.6502) by AlliedModders LLC
  10 "Basic Commands" (1.10.0.6502) by AlliedModders LLC
  11 "Fun Commands" (1.10.0.6502) by AlliedModders LLC
  12 "Discord API" (0.1.103) by Deathknife
  13 "SurfTimer" (285) by Ace & olokos
  14 "[Source 2013] Custom Chat Colors" (3.1.0 CP) by Dr. McKay, Fixed up by Keith Warren (Drixevel)
  15 "Basic Votes" (1.10.0.6502) by AlliedModders LLC
  16 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Shaders Allen)
  17 "Admin File Reader" (1.10.0.6502) by AlliedModders LLC
  18 "Fun Votes" (1.10.0.6502) by AlliedModders LLC
  19 "Admin Help" (1.10.0.6502) by AlliedModders LLC
  20 "Basic Chat" (1.10.0.6502) by AlliedModders LLC
  21 "Basic Ban Commands" (1.10.0.6502) by AlliedModders LLC
  22 "Client Preferences" (1.10.0.6502) by AlliedModders LLC
  23 "Nextmap" (1.10.0.6502) by AlliedModders LLC

![image](https://user-images.githubusercontent.com/16320628/114288113-e4c20c80-9a6c-11eb-8d65-c326684ada7e.png)

**Comment by S0ulan** [comment]
![image](https://user-images.githubusercontent.com/16320628/114288107-daa00e00-9a6c-11eb-9932-5f0d5721be3a.png)

**Comment by Kyli3Boi** [comment]
Can you show what is in your ck_maptier table

**Comment by S0ulan** [comment]
> Can you show what is in your ck_maptier table

![image](https://user-images.githubusercontent.com/16320628/114303448-7ada4f00-9ace-11eb-94e3-2e745c9e6192.png)

**Comment by S0ulan** [comment]
Ok forgot to insert other maps manually
