### ISSUE TITLE
[BUG] Map filters being ignored

### ISSUE THREAD

**Issue by ImDini** [surftimer/Surftimer-Official#279]
**Describe the bug**
If any surf map has a filter of any type it will just be ignored. Pretty much renders all maps with filters broken.

**Expected behavior**
to correctly read filter_activators and not change it's name that is read by default everywhere else

**Comment by ImDini** [comment]
#108

**Comment by Ciallo-Ani** [comment]
as it's mensioned again, i find it **unneccessary to set player's targetname** when they start to touch ck_zones,while ck_zones' targetname is neccessary

i couldn't tell you more about it, but delete some code they implemented badly should be ok.

 i haven't test it  :d

https://github.com/surftimer/Surftimer-Official/blob/master/addons/sourcemod/scripting/surftimer/surfzones.sp#L225
