### ISSUE TITLE
[BUG] Timer is inaccurate

### ISSUE THREAD

**Issue by t5mat** [surftimer/Surftimer-Official#282]
**Describe the bug**
Copied from discussion in the discord.

These 2 issues make the timer inaccurate,

1. Run time is calculated using GetGameTime(). This is bad because time should be based on playercmds and not server frames, since multiple playercmds may be processed in a single frame. Instead code should count PostThink()s or some shit and use this as time, for example - https://github.com/rumourA/End-Touch-Fix/blob/72e7dc745371e91853b19c7e0980ae8953fb9e62/scripting/BareTimer.sp#L96

https://github.com/surftimer/Surftimer-Official/blob/b6a71e9ebde21cb865464c932de116baec199bf6/addons/sourcemod/scripting/surftimer/buttonpress.sp#L189

2. (I guess this one becomes relevant after fixing 1) The engine calls EndTouch()s at the end of each server frame, not after each ProcessMovement. So if multiple playercmds are processed in 1 frame, EndTouch might be delayed by a few "player ticks". Fix is fairly simple - https://github.com/rumourA/End-Touch-Fix/blob/72e7dc745371e91853b19c7e0980ae8953fb9e62/scripting/EndTouchFix.sp#L73

**Comment by DaLLuZZ** [comment]
I think `GetGameFrameTime()` should be used instead of `GetTickInterval()` there. Because `GetTickInterval()` always returns the same value no matter how long it took the server to process one frame. But `GetGameFrameTime()` returns the real time the server took to process the last frame. What do you think about this, colleagues?

**Comment by t5mat** [comment]
Run time calculation should not be dependent on the time it takes for the server to process gameframes. Each "player tick" length is exactly what GetTickInterval() returns, i.e. in a 100tick server there are exactly 100 player ticks/movements per second.

**Comment by Bara** [comment]
Times should accurate as possible. Server performance isn't always equal especially if you host multiple services on the same server like webserver, mysql and other stuff. You could get better times when servers runs better or worse and under this conditions you can get records which are "impossible".

**Comment by Ciallo-Ani** [comment]
**GetGameFrameTime()** returns the actual delta from the last frame, which can solve issues with server lag affecting times at high cpu usage.

I think it's more accurate than **GetTickInterval()** because the performance of a player depends in part on the performance of the server.

**Comment by t5mat** [comment]
`GetTickInterval()` returns the server tickrate. It will always return the same value

Want to emphasize again that simulated time != real time (GetEngineTime, GetGameFrameTime).

Run time should be calculated with simulated time and should not depend on real time.

Server processing time, lag, CPU usage, etc have nothing to do with simulated time. The server processes an arbitrary amount of player ticks per frame.

Your goal is to calculate the time between startzone's EndTouch and endzone's StartTouch. These callbacks are called in player ticks, so the measurement should be exactly `(endEndTouchPlayerTick - startEndTouchPlayerTick) * GetTickInterval()`

**Comment by tslashd** [comment]
Anything currently in the works for resolving this issue?
