### ISSUE TITLE
[Suggestion] Make Dhooks as requirement in dev branch

### ISSUE THREAD

**Issue by Ciallo-Ani** [surftimer/Surftimer-Official#295]
I want to make timer more accurate. #282
Addtionally, it could be useful if we want adding more features in the future

**Comment by Bara** [comment]
For which function you'll need dhooks?

**Comment by Ciallo-Ani** [comment]
**CGameMovement::ProcessMovement** at least
I'm considering writing it into the dev branch so that if there is an issue with it that it can be sorted out before becoming official

**Comment by Bara** [comment]
I wouldn't touch the dev branch, we should rename dev branch to something like `NeverTouchThis` 😂

**Comment by Ciallo-Ani** [comment]
so what should i do if i want to add something new that haven't tested enough :joy:

**Comment by 1zc** [comment]
Fork master, test it, PR it - maybe a new branch? :P

**Comment by Ciallo-Ani** [comment]
> Fork master, test it, PR it - maybe a new branch? :P

i'm awaiting for a new branch like bhoptimer's very_good_yes 😢

**Comment by Bara** [comment]
I see no real reasons for this. Having 2 branches is just annoying, especially when someone modify/merge stuff in the wrong branch (like the current situation here). Personally I like the rolling release idea, simply mark specific a commit as stable and create a tag (or new branch).

And your PR is in theory a new branch, just not in the public repo.
