### ISSUE TITLE
[BUG] Bugged wrcp's

### ISSUE THREAD

**Issue by dPexxIAM** [surftimer/Surftimer-Official#307]
**Describe the bug**
The timer seems to freeze after completing a stage & doesn't register your completion, then, if you fail the stage right after it register's your completion for the NEXT stage which you haven't even completed yet.

**Expected behavior**
The timer should register stage completion every time.

**Screenshots**
https://www.youtube.com/watch?v=V0xLQ9PcboI

**Plugin List**
N/A

**Additional context**
[SM] Exception reported: Invalid index -1 (count: 1887)
 [SM] Blaming: surftimer.smx
 [SM] Call stack trace:
 [SM]   [0] GetArrayArray
 [SM]   [1] Line 1324, surftimer/replay.sp::Stage_SaveRecording
 [SM]   [2] Line 1061, surftimer/buttonpress.sp::CL_OnEndWrcpTimerPress
 [SM]   [3] Line 410, surftimer/surfzones.sp::StartTouch
 [SM]   [4] Line 241, surftimer/surfzones.sp::StartTouchTrigger

**Comment by DaLLuZZ** [comment]
do you know a way to reproduce this?

**Comment by Ciallo-Ani** [comment]
stage1 to stage2 bug?

**Comment by dPexxIAM** [comment]
> do you know a way to reproduce this?

Sadly no, it happens randomly and i have not been able to find out a way to reproduce it reliably.


> stage1 to stage2 bug i think?

Nope, different. Stage 1>Stage 2 bug was hack fixed
