### ISSUE TITLE
[BUG] SurfTimer.sp Cannot Read From File: autoexecconfig

### ISSUE THREAD

**Issue by Sidicer** [surftimer/Surftimer-Official#352]
**Describe the bug**
After downloading every extention, include, 1.0.3 Version of SurfTimer (from Releases) and trying to Compile it:
`SurfTimer.sp(21) : fatal error 183: cannot read from file: "autoexecconfig"`

I have checked every single plugin, extention, repo mentioned and forum and nowhere is there "autoexecconfig.inc" inside
`addons/sourcemod/scripting/include`

**Expected behavior**
SurfTimer.sp to complete compilation without an error, as every single .sp file, include and extension is as per README.md

**Screenshots**
![image](https://user-images.githubusercontent.com/9251667/142049487-89adef12-da19-4ed2-b054-6758528df45c.png)

**Plugin List**
Plugins are not related to compilation.

**Additional context**
I could not even find "autoexecconfig" reference anywhere in this repo, other repos, forums or tutorials.
autoexecconfig.inc does not even exist anywhere related to SurfTimer or any other mentioned plugins/includes

**Comment by Bara** [comment]
You need [this file](https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc). Move it to your `scripting/includes` folder.

**Comment by Sidicer** [comment]
Downloading [[INCLUDE] AutoExecConfig: Read and append to auto configs](https://forums.alliedmods.net/showthread.php?t=204254) manually resolved the issue.

Please add this to required includes/repos or Readme!

**Comment by sneak-it** [comment]
> Please add this to required includes/repos or Readme!

Yep, that should be done before this is closed out.
