### ISSUE TITLE
[BUG] No sound played and no time difference shown on map recs

### ISSUE THREAD

**Issue by tslashd** [surftimer/Surftimer-Official#375]
**Describe the bug**
Upon beating a record of a map, no sound is being played and also time difference between previous SR is not shown.

**Expected behavior**
Play a sound and show difference in time between current SR and previous one

**Screenshots**
None

**Plugin List**
SurfTimer 1.0.5 release, including #372 _(which fixes multiple surftimer_OnNewRecord calls)_

**Comment by dPexxIAM** [comment]
should be fixed with https://github.com/surftimer/Surftimer-Official/pull/381
