### ISSUE TITLE
[BUG] Styled Map and Bonus SR's not forwarded correctly

### ISSUE THREAD

**Issue by tslashd** [surftimer/Surftimer-Official#382]
**Describe the bug**
**_surftimer_OnNewRecord_** does not seems to work correctly for styled map or bonus completions

**Expected behavior**
Image taken from a server using a fork (not latest master) but behavior should be the same.
![image](https://user-images.githubusercontent.com/74899888/151379820-cc7b0c7e-4256-40b2-89a9-98ecab1ddd8c.png)

**Plugin List**
_SurfTimer 1.0.6
SurfTimer-Discord 2.1.3_

**Additional context**
The issue does NOT come from _SurfTimer-Discord 2.1.3_

**Screenshots**
**_Styled Stage + Map recs_**
In-game:
![image](https://user-images.githubusercontent.com/74899888/151327424-ed6253e2-b000-4352-8542-46c036c671d1.png)

Discord (other 2 stages are up there as well):
![image](https://user-images.githubusercontent.com/74899888/151327700-7b526c07-2206-4531-91bc-ef8b82c41a43.png)

**_Normal Stage + Map recs_**
In-game:
![image](https://user-images.githubusercontent.com/74899888/151327862-52629a1e-50d8-4fbf-8c5f-136e10c7f6a9.png)

Discord (other 2 stages are up there as well):
![image](https://user-images.githubusercontent.com/74899888/151327963-4bf33d22-a8d2-406f-9812-d2c12c110b0f.png)

**Comment by dPexxIAM** [comment]
@Sarrus1
