### ISSUE TITLE
[BUG] Rank Table empty / no points awarded

### ISSUE THREAD

**Issue by zeddy1234** [surftimer/Surftimer-Official#413]
**Describe the bug**
Hey , just setup a new server, the rank table is always empty. All other tables such as ranks etc are updated when players beat the map, but no one ever gets points.

**Expected behavior**
Players should get points after beating maps but they dont

**Screenshots**
![Screenshot_82](https://user-images.githubusercontent.com/31687806/162608852-4ad91867-b367-4e85-92fd-19f31971f4a3.png)

**Additional context**
Updated mapcycle etc everything, tested with multiple players beating multiple maps.
Also
SurfTimer | ZeddY^ is ranked 99999/0 with 0 points
L 04/10/2022 - 14:32:10: [SurfTimer.smx] [SurfTimer] SQL Error (sql_CountFinishedMapsCallback): Subquery returns more than 1 row

**Comment by dPexxIAM** [comment]
Make sure your maps have tiers. You can add a tier to a map using sm_amt command.

Or import the sql file here https://github.com/surftimer/Surftimer-Official/blob/master/scripts/mysql-files/ck_maptier.sql
