### ISSUE TITLE
[BUG] Using any !style ignores the zone max prespeed

### ISSUE THREAD

**Issue by breakthegreat** [surftimer/Surftimer-Official#53]
**Describe the bug**
Using any style will ignore the zone prespeed limit, attached a screenshot of low gravity still where I can go over 350 u/s limit in the start zone
**Expected behavior**
Style should not ignore start zone prespeed limits. 
**Screenshots**
![image](https://user-images.githubusercontent.com/64219376/80136330-8bb54c00-856f-11ea-892a-17788c084ed0.png)

**Additional context**
Was an issue back in the older version of surftimer (274).

**Comment by 13ace37** [comment]
This is not 100% true. Also, you could simply enable the one jump limit for the zones.

**Comment by breakthegreat** [comment]
I know but one jump limit is somewhat weird for people who plays on the server, they don't really like it, but definetely i'd put this one jump limit if it can't be fixed

**Comment by breakthegreat** [comment]
To be more specific, this bug only appears with fun styles (ranked seems to work fine)

**Comment by sneak-it** [comment]
If I'm understanding correctly, you want a hard start zone speed cap, if so use `ck_limit_speed_type 0`.

**Comment by breakthegreat** [comment]
ck_limit_speed_type did the trick, i'm assuming I should put this on from now on, but surftimer way to limit speed is so much better. Idk if this style issue will be fixed anytime soon, but doesn't really matter as much as it is mostly affecting fun styles.

**Comment by olokos** [comment]
Is `ck_limit_speed_type 0` going to completely disable speed limiter?
I'd love some more insight into it, please.

**Comment by freakexeuLow** [comment]
I have a similar problem, maybe it'll help...here a small video where a user leaves the zone with a prespeed of 500 speed :3
the value in cfg is set to: ck_limit_speed_type "1"

[https://youtu.be/2EjATUBA628](https://youtu.be/2EjATUBA628)

**Comment by sneak-it** [comment]
Not sure how this is an issue... the way `ck_limit_speed_type 1` works is by only limiting speed if a bhop is performed. Legitimate prestrafing on the ground and in the air (without bhop) is uncapped.

**Comment by freakexeuLow** [comment]
> 
> 
> Not sure how this is an issue... the way `ck_limit_speed_type 1` works is by only limiting speed if a bhop is performed. Legitimate prestrafing on the ground and in the air (without bhop) is uncapped.

Hey sneaK :3 
good to know, many of the users write with me that it is abusing and i was thinking the prespeed is normal capped 350 everytime ^^

**Comment by sneak-it** [comment]
Hey there :) You can do that with `ck_limit_speed_type 0`

**Comment by freakexeuLow** [comment]
sneaK, then they complain again why you only get 250 speed without moving, we tested it and unfortunately and the users are also dissatisfied with it :/
But thanks for your help

**Comment by 13ace37** [comment]
Setting to speedlimit to 350 and the limit type to 0 should allow the players to got to 350 xy units but not higher.
https://youtu.be/jEbpzt4DzUo

**Comment by freakexeuLow** [comment]
was the command for the prespeed removed, at that time it was still to be seen in the Surftimer.cfg
(ck_prespeed_limit_start) currently you can only find the surf types^^

**Comment by 13ace37** [comment]
As far as I can remember there was never a cvar for this. You can set the prespeed for each zone separately. Either in the zone settings on within the ck_zones table.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
I am able to reproduce this.

**More info** once you leave the zone and re-enter the zone then it obeys the pre-speed

**Comment by qawery-just-sad** [comment]
@Kyli3Boi  can you test with #208 and tell if that fixes it?

**Comment by olokos** [comment]
Seems to be resolved, let us know if it still happens.
