### ISSUE TITLE
[BUG] !profile ---> show completed maps --->map PR are all top 1

### ISSUE THREAD

**Issue by breakthegreat** [surftimer/Surftimer-Official#60]
**Describe the bug**
When using !profile, and then selecting completed maps it shows all the map in console completed as rank 1/xxxx

**Expected behavior**
Should be displaying real rank.

**Screenshots**

![image](https://user-images.githubusercontent.com/64219376/80271183-d9bf7200-868b-11ea-9ab8-29682615134d.png)

**Comment by dPexxIAM** [comment]
Tested myself, I don't have this issue present. Are you using the compiled release version or compiling it by yourself?

**Comment by qawery-just-sad** [comment]
same issue release 285

**Comment by dPexxIAM** [comment]
weird, I don't seem to have the issue. i guess someone else can look into it further.

https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L2651

**Comment by g2dgaming** [comment]
i'm also facing same issue

**Comment by breakthegreat** [comment]
Using 285 release

**Comment by freakexeuLow** [comment]
I have the same problem. I had the cksurf timer still running (the one from St00ne). After that I ran the upgrade script and restarted it again with the SurfTimer. There were no errors in the database, also the server logs were clean, so I could not find or explain the error after that the problem was also there what the other users report here. Here are some pictures, I can also create a test server where someone can tinker with the problem :3

![RankProblem1](https://user-images.githubusercontent.com/32603929/80375614-e369f500-8898-11ea-8ca4-5891c6241cfe.png)
![RankProblem2](https://user-images.githubusercontent.com/32603929/80375618-e49b2200-8898-11ea-8e1e-061e45ae1a82.png)
![RankProblem3](https://user-images.githubusercontent.com/32603929/80375620-e664e580-8898-11ea-8f23-ec2ccb0d62a5.png)

**Comment by LubricantJam** [comment]
Doesn't happen for me.

**Comment by freakexeuLow** [comment]
> 
> 
> Doesn't happen for me.

we tried it 3-4 times, we could not explain the problem either. I have written everything that is needed as information and you didn't use the cksurf timer before?

**Comment by Caaine** [comment]
same problem  :(

**Comment by LubricantJam** [comment]
> > Doesn't happen for me.
> 
> we tried it 3-4 times, we could not explain the problem either. I have written everything that is needed as information and you didn't use the cksurf timer before?

No, I upgraded from a fluffys fork. Maybe you should check to see if the upgrade script for ckSurf is actually even working. 

Can you show me the schema for your ck_playerrank & ck_maptier?

**Comment by LubricantJam** [comment]
Or try and run this query (replace steam ID with one of yours, and if it doesn't return rows then you've got missing structure. 

```
SELECT db1.name, db2.steamid, db2.mapname, db2.runtimepro as overall, db1.steamid, db3.tier FROM ck_playertimes as db2 INNER JOIN ck_playerrank as db1 on db2.steamid = db1.steamid INNER JOIN ck_maptier AS db3 ON db2.mapname = db3.mapname WHERE db2.steamid = 'STEAM_1:1:96874781' AND db2.style = 0 AND db1.style = 0 AND db2.runtimepro > -1.0 ORDER BY mapname ASC;

**Comment by Caaine** [comment]
https://pastebin.com/pmkVN4PY

**Comment by LubricantJam** [comment]
Is your overall actually comma seperated and not period?

**Comment by freakexeuLow** [comment]
> 
> 
> > > Doesn't happen for me.
> > 
> > 
> > we tried it 3-4 times, we could not explain the problem either. I have written everything that is needed as information and you didn't use the cksurf timer before?
> 
> No, I upgraded from a fluffys fork. Maybe you should check to see if the upgrade script for ckSurf is actually even working.
> 
> Can you show me the schema for your ck_playerrank & ck_maptier?

The upgrade script ran perfectly and also without problems. I will create a test server later, currently the servers is running now with cksurf again because i could not fix the problem. The other servers did not have this problem (servers were also rebuilt) + that the database was completely fresh 
I used this plugin before: [https://github.com/StAwN74/ckSurf-1.18kd-Release](https://github.com/StAwN74/ckSurf-1.18kd-Release)

**Comment by Caaine** [comment]
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_pox_revamp_csgo', 'Caaine', '41.1719', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_Rebel_scaz_njv', 'Caaine', '38.0156', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_reytx_csgo', 'Caaine', '70.25', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_simpsons_go_rc2_csgo', 'Caaine', '399.5', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_singletons_csgo', 'Caaine', '98.9062', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_southpark_refix', 'Caaine', '202.719', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_summit_csgo', 'Caaine', '54.7812', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_trance_csgo', 'Caaine', '100.469', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_utopia', 'Caaine', '62.9844', '0');
INSERT INTO `ck_playertimes` VALUES ('STEAM_1:1:31709476', 'surf_utopia_night_csgo', 'Caaine', '63.4375', '0');

**Comment by freakexeuLow** [comment]
@LubricantJam 
Here you have the tables (standard tables from cksurf) without the upgrade or anything else. If you need the upgrade, you will have to wait until later because I don't have a test server running at the moment.
[ck_maptier.zip](https://github.com/olokos/Surftimer-olokos/files/4540084/ck_maptier.zip)
[ck_playerrank.zip](https://github.com/olokos/Surftimer-olokos/files/4540085/ck_playerrank.zip)

**Comment by LubricantJam** [comment]
Yeah, your database isn't upgraded to the new table structure...

This is yours:
```
CREATE TABLE `ck_playerrank` (
  `steamid` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `points` int(12) DEFAULT 0,
  `winratio` int(12) DEFAULT 0,
  `pointsratio` int(12) DEFAULT 0,
  `finishedmaps` int(12) DEFAULT 0,
  `multiplier` int(12) DEFAULT 0,
  `finishedmapspro` int(12) DEFAULT 0,
  `lastseen` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
and this is ours:
https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/db/queries.sp#L50

**Comment by freakexeuLow** [comment]
> 
> 
> Yeah, your database isn't upgraded to the new table structure...
> 
> This is yours:
> 
> ```
> CREATE TABLE `ck_playerrank` (
>   `steamid` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
>   `name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
>   `country` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
>   `points` int(12) DEFAULT 0,
>   `winratio` int(12) DEFAULT 0,
>   `pointsratio` int(12) DEFAULT 0,
>   `finishedmaps` int(12) DEFAULT 0,
>   `multiplier` int(12) DEFAULT 0,
>   `finishedmapspro` int(12) DEFAULT 0,
>   `lastseen` date DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
> ```
> 
> and this is ours:
> https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/db/queries.sp#L50
> 
> Which indicates, you didn't run the SQL upgrade script here:
> https://github.com/olokos/Surftimer-olokos/blob/dev/scripts/mysql-files/upgrading/upgrade-niko.sql

Did you even read what I wrote? I EXACTLY wrote that what I sent is the normal cksurf.sql file without any upgrade. I had done the upgrade before, the problems I wrote above were after the upgrade.

Here are the two files after the upgrade, I just found time for it.
[ck_playerrank.zip](https://github.com/olokos/Surftimer-olokos/files/4540666/ck_playerrank.zip)
[ck_maptier.zip](https://github.com/olokos/Surftimer-olokos/files/4540667/ck_maptier.zip)

**Comment by LubricantJam** [comment]
> > Yeah, your database isn't upgraded to the new table structure...
> > This is yours:
> > ```
> > CREATE TABLE `ck_playerrank` (
> >   `steamid` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
> >   `name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> >   `country` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> >   `points` int(12) DEFAULT 0,
> >   `winratio` int(12) DEFAULT 0,
> >   `pointsratio` int(12) DEFAULT 0,
> >   `finishedmaps` int(12) DEFAULT 0,
> >   `multiplier` int(12) DEFAULT 0,
> >   `finishedmapspro` int(12) DEFAULT 0,
> >   `lastseen` date DEFAULT NULL
> > ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
> > ```
> > 
> > 
> > and this is ours:
> > https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/db/queries.sp#L50
> > Which indicates, you didn't run the SQL upgrade script here:
> > https://github.com/olokos/Surftimer-olokos/blob/dev/scripts/mysql-files/upgrading/upgrade-niko.sql
> 
> Did you even read what I wrote? I EXACTLY wrote that what I sent is the normal cksurf.sql file without any upgrade. I had done the upgrade before, the problems I wrote above were after the upgrade.
> 
> Here are the two files after the upgrade, I just found time for it.
> [ck_playerrank.zip](https://github.com/olokos/Surftimer-olokos/files/4540666/ck_playerrank.zip)
> [ck_maptier.zip](https://github.com/olokos/Surftimer-olokos/files/4540667/ck_maptier.zip)

So what is your problem? You say it doesn't work, you don't use latest structure and you complain? Am I missing something here? How am I to help you with your issue when you don't even give the right data to look along side it. If I wanted ck data I would've asked for it.

**Comment by freakexeuLow** [comment]
Please read carefully, the problem I described here was with the upgrade 
Click me: [https://github.com/olokos/Surftimer-olokos/issues/60#issuecomment-619975176](https://github.com/olokos/Surftimer-olokos/issues/60#issuecomment-619975176)

Afterwards I added the old database again, you wrote me that I should send you the 2 things. In the description it was also written that they are without the upgrade, after that I told them that if I find the time, I will create a server and send them the files with the upgrade script from the sql file. Now you write in your mail, that the tables are not in it, where I also wrote this before, that they are the normal tables without the upgrade.

**Comment by LubricantJam** [comment]
> Please read carefully, the problem I described here was with the upgrade
> Click me: [#60 (comment)](https://github.com/olokos/Surftimer-olokos/issues/60#issuecomment-619975176)
> 
> Afterwards I added the old database again, you wrote me that I should send you the 2 things. In the description it was also written that they are without the upgrade, after that I told them that if I find the time, I will create a server and send them the files with the upgrade script from the sql file. Now you write in your mail, that the tables are not in it, where I also wrote this before, that they are the normal tables without the upgrade.

So why didn't you report the errors you were receiving on the new structure?

**Comment by freakexeuLow** [comment]
> 
> 
> > Please read carefully, the problem I described here was with the upgrade
> > Click me: [#60 (comment)](https://github.com/olokos/Surftimer-olokos/issues/60#issuecomment-619975176)
> > Afterwards I added the old database again, you wrote me that I should send you the 2 things. In the description it was also written that they are without the upgrade, after that I told them that if I find the time, I will create a server and send them the files with the upgrade script from the sql file. Now you write in your mail, that the tables are not in it, where I also wrote this before, that they are the normal tables without the upgrade.
> 
> So why didn't you report the errors you were receiving on the new structure?

You didn't say exactly what they wanted. If you had meant the ones with the new structure, I would have sent them those too. But I also wrote it in my post that the ones I sent first were without all that, the 2nd one only has the upgrades. Never mind now, let's take care of the problem that other people have reported as a problem^^

**Comment by Caaine** [comment]
on Dev Version working fine on master bugged and all top 1

**Comment by olokos** [comment]
Thanks @Caaine 
master will be updated once dev is stable enough
