### ISSUE TITLE
[Suggestion] Add ConVar to disable droping knife after typing knife.

### ISSUE THREAD

**Issue by KristianP26** [surftimer/Surftimer-Official#79]
[Suggestion] Add ConVar to disable droping knife after typing knife.

**Comment by LubricantJam** [comment]
Would you like to give it a go yourself in a PR? Could be nice to slowly teach yourself how to become a contributor. Of course, we will review it for you :)

**Comment by TheGunter24** [comment]
If you want to disable knife drop completely -> https://github.com/olokos/Surftimer-olokos/blob/dev/cfg/sourcemod/surftimer/main.cfg#L27

**Comment by KristianP26** [comment]
@TheGunter24 I mean when you type !knife you get a knife and if you already have one they will stack.

**Comment by KristianP26** [comment]
And its buggy when you use plugin for knifes and skins.

**Comment by sneak-it** [comment]
> @TheGunter24 I mean when you type !knife you get a knife and if you already have one they will stack.

This is an easy fix to add a GetPlayerWeaponSlot check on the knife slot to ensure there is no existing weapon there: https://github.com/olokos/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/commands.sp#L4047

> And its buggy when you use plugin for knifes and skins.

Sounds like more of an issue with the plugin you use for knives/skins, we won't support that here.

**Comment by KristianP26** [comment]
nah thats inside of surftimer, because that plugins dontdrop you knife.

**Comment by Kyli3Boi** [comment]
This can be closed...
