### ISSUE TITLE
[BUG] One Jump limit Bug

### ISSUE THREAD

**Issue by KristianP26** [surftimer/Surftimer-Official#86]
https://www.youtube.com/watch?v=add5fJYLRQ8&feature=youtu.be

When you jumping and jumping in start zone one jump limit disappear.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
Am able to reproduce

"SurfTimer" (1.1.0-dev)
